### ISSUE TITLE
Inkscape crashes under KDE4 with gtk2 theme set to qtcurve

### ISSUE THREAD

**Issue by FadeMind** [QtCurve/qtcurve-gtk2#3]
FS#43631: https://bugs.archlinux.org/task/43631
Soft version:
 inkscape 0.91-1
lib32-qtcurve-gtk2 1.8.18-1
lib32-qtcurve-qt4 1.8.18-1
lib32-qtcurve-utils 1.8.18-1
qtcurve-gtk2 1.8.18-3
qtcurve-kde4 1.8.18-3
qtcurve-qt4 1.8.18-3
qtcurve-qt5 1.8.18-3
qtcurve-utils 1.8.18-3
Inkscape have memory leak under QtCurve theme:
[tomasz@arch ~]$ inkscape 

Emergency save activated!
Emergency save completed. Inkscape will close now.
If you can reproduce this crash, please file a bug at www.inkscape.org
with a detailed description of the steps leading to the crash, so we can fix it.
Terminated

I'm using KZukitwo theme.
But when I select GTK Theme instead QtCurve Inkscape app working fine. IMO QtCurve regression.

![zaznaczenie_131](https://cloud.githubusercontent.com/assets/9846948/5979514/ad321a10-a8a8-11e4-8d82-05db1d10e54c.png)

inkscape crash with qtcurve breeze: https://www.youtube.com/watch?v=x1W1sYEndo8&feature=youtu.be

**Comment by yuyichao** [comment]
What do you mean by "But when I select GTK Theme instead QtCurve Inkscape app working fine. IMO QtCurve regression."

Also, please report to the kde bug tracker.

**Comment by yuyichao** [comment]
https://bugs.kde.org/

**Comment by yuyichao** [comment]
https://bugs.kde.org/enter_bug.cgi?product=QtCurve&format=guided

**Comment by spaeps** [comment]
@yuyichao I confirm the bug.
In gtk2/style/qtcurve.c line 375 if detail is NULL
the check strcmp(detail, "checkbutton") != 0 ) will segfault.

I solved by testing it for not being NULL before checking:
https://gist.github.com/anonymous/8e6e4ea32dabf03cf630

Sorry for not filing a new bug on the KDE bts.

**Comment by cyberang3l** [comment]
I faced the same problem and your patch fixes the issue :+1:

**Comment by goetzc** [comment]
Could this patch be applied and release a version containing it? As it would prevent Inkscpae crash when using QtCurve-gtk2

**Comment by lindhe** [comment]
Is this still not in master??
